package edu.psu.alexaskill.request_handlers.send_email;

import org.apache.commons.lang3.text.WordUtils;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;

public class EmailCorrector
{
    private Map<String, String> CorrectionsMap = new HashMap<>();

    public EmailCorrector()
    {
        CorrectionsMap.put("ey", "a");
        CorrectionsMap.put("be", "b");
        CorrectionsMap.put("bee", "b");
        CorrectionsMap.put("see", "c");
        CorrectionsMap.put("sea", "c");
        CorrectionsMap.put("dee", "d");
        CorrectionsMap.put("gee", "g");
        CorrectionsMap.put("eye", "i");
        CorrectionsMap.put("jay", "j");
        CorrectionsMap.put("oh", "o");
        CorrectionsMap.put("pee", "p");
        CorrectionsMap.put("pea", "p");
        CorrectionsMap.put("queue", "q");
        CorrectionsMap.put("que", "q");
        CorrectionsMap.put("are", "r");
        CorrectionsMap.put("tea", "t");
        CorrectionsMap.put("tee", "t");
        CorrectionsMap.put("you", "u");
        CorrectionsMap.put("double you", "w");
        CorrectionsMap.put("ex", "x");
        CorrectionsMap.put("why", "y");
    }

    public String CorrectAddress(String address)
    {
        String correctedAddress;

        if(address.contains(" "))
        {
            String[] splitAddress = address.split("\\s+");
            for(int i = 0; i < splitAddress.length; i++)
            {
                for(String key: CorrectionsMap.keySet())
                {
                    if(splitAddress[i].equals(key))
                    {
                        splitAddress[i] = CorrectionsMap.get(key);
                    }
                }
            }

            correctedAddress = Arrays.stream(splitAddress).collect(Collectors.joining(""));
        }
        else
        {
            correctedAddress = address; //No changes
        }

        return correctedAddress;
    }

    public String CorrectSubject(String subject)
    {
        return WordUtils.capitalize(subject);
    }

    public String CorrectBody(String body)
    {
        body += "\\n\\nThis email has been generated by an Amazon Echo device.";
        return body;
    }


}
